In [1]:
# 导入 PyTorch
import torch

# 创建一个张量
x = torch.tensor([1.0, 2.0, 3.0])
print("张量 x:", x)

# 张量加法
y = torch.tensor([4.0, 5.0, 6.0])
z = x + y
print("张量 z (x + y):", z)

张量 x: tensor([1., 2., 3.])
张量 z (x + y): tensor([5., 7., 9.])


In [2]:
import torch

# 设置数据类型和设备
dtype = torch.float  # 张量数据类型为浮点型
device = torch.device("cpu")  # 本次计算在 CPU 上进行

# 创建并打印两个随机张量 a 和 b
a = torch.randn(2, 3, device=device, dtype=dtype)  # 创建一个 2x3 的随机张量
b = torch.randn(2, 3, device=device, dtype=dtype)  # 创建另一个 2x3 的随机张量

print("张量 a:")
print(a)

print("张量 b:")
print(b)

# 逐元素相乘并输出结果
print("a 和 b 的逐元素乘积:")
print(a * b)

# 输出张量 a 所有元素的总和
print("张量 a 所有元素的总和:")
print(a.sum())

# 输出张量 a 中第 2 行第 3 列的元素（注意索引从 0 开始）
print("张量 a 第 2 行第 3 列的元素:")
print(a[1, 2])

# 输出张量 a 中的最大值
print("张量 a 中的最大值:")
print(a.max())

张量 a:
tensor([[ 0.6253, -0.2465,  0.5833],
        [ 0.0542,  0.9521, -0.7355]])
张量 b:
tensor([[ 0.9798, -0.4585, -0.3305],
        [ 1.0549,  0.0861, -0.5733]])
a 和 b 的逐元素乘积:
tensor([[ 0.6127,  0.1130, -0.1928],
        [ 0.0572,  0.0820,  0.4217]])
张量 a 所有元素的总和:
tensor(1.2329)
张量 a 第 2 行第 3 列的元素:
tensor(-0.7355)
张量 a 中的最大值:
tensor(0.9521)
