In [ ]:
''''
'张量（Tensor）是 PyTorch 中的核心数据结构，用于存储和操作多维数组。

张量可以视为一个多维数组，支持加速计算的操作。

在 PyTorch 中，张量的概念类似于 NumPy 中的数组，但是 PyTorch 的张量可以运行在不同的设备上，比如 CPU 和 GPU，这使得它们非常适合于进行大规模并行计算，特别是在深度学习领域。

维度（Dimensionality）：张量的维度指的是数据的多维数组结构。例如，一个标量（0维张量）是一个单独的数字，一个向量（1维张量）是一个一维数组，一个矩阵（2维张量）是一个二维数组，以此类推。
(衡量性质的量的多少，如七天的温度，维度只有温度一维，多个人的成绩，既要展示人，也要展示成绩，是二维的，一周班级每个人每天都成绩，显然是三维的)

形状（Shape）：张量的形状是指每个维度上的大小。例如，一个形状为(3, 4)的张量意味着它有3行4列。

数据类型（Dtype）：张量中的数据类型定义了存储每个元素所需的内存大小和解释方式。PyTorch支持多种数据类型，包括整数型（如torch.int8、torch.int32）、浮点型（如torch.float32、torch.float64）和布尔型（torch.bool）。'
'''

import torch

# 创建一个 2x3 的全 0 张量
a = torch.zeros(2, 3)
print(a)

# 创建一个 2x3 的全 1 张量
b = torch.ones(2, 3)
print(b)

# 创建一个 2x3 的随机数张量
c = torch.randn(2, 3)
print(c)

# 从 NumPy 数组创建张量
import numpy as np
numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

# 在指定设备（CPU/GPU）上创建张量
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
d = torch.randn(2, 3, device=device)
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-1.7078,  0.4638, -2.0887],
        [ 0.1624,  1.4070, -0.3669]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[-0.0375, -0.6789, -0.3075],
        [-0.7600, -0.3400, -0.1609]])


In [ ]:
#常用张量操作：
# 张量相加
import torch
e = torch.randn(2, 3)
f = torch.randn(2, 3)
print(e)
print(f)
print(e + f)

# 逐元素乘法
print(e * f)

# 张量的转置,将张量的行和列交换（即转置）。
g = torch.randn(3, 2)
print(g.t())  # 或者 g.transpose(0, 1)

# 张量的形状
print(g.shape)  # 返回形状

tensor([[ 0.8461,  1.0579, -0.4861],
        [-1.2303, -0.6165,  0.6683]])
tensor([[ 1.0630, -0.5015,  0.2411],
        [-1.9848, -0.4840, -0.3619]])
tensor([[ 1.9090,  0.5564, -0.2450],
        [-3.2151, -1.1005,  0.3065]])
tensor([[ 0.8993, -0.5305, -0.1172],
        [ 2.4420,  0.2984, -0.2418]])
tensor([[-0.3368,  2.3462,  1.4429],
        [ 0.5862,  0.0476, -0.1127]])
torch.Size([3, 2])


In [ ]:
#PyTorch的张量支持自动微分，这是深度学习中的关键特性。当你创建一个需要张量的梯度时，PyTorch可以自动计算其梯度：
import torch
# 创建一个需要梯度的张量
tensor_requires_grad = torch.tensor([1.0], requires_grad=True)
print(tensor_requires_grad)
# 进行一些操作
tensor_result = tensor_requires_grad * 2

# 计算梯度,梯度是权重的校准方向，乘学习率得到权重的校准值，学习率指的是每次权重更新以达到最低损失的步长
tensor_result.backward()
print(tensor_requires_grad.grad)  # 输出梯度

tensor([1.], requires_grad=True)
tensor([2.])


In [7]:
# 创建一个需要计算梯度的张量
import torch
x = torch.randn(2, 2, requires_grad=True)
print(x)

# 执行某些操作
y = x + 2
z = y * y * 3
out = z.mean()

print(out)
# 反向传播，计算梯度
out.backward()

# 查看 x 的梯度
print(x.grad)

tensor([[ 0.6094, -0.0760],
        [-1.2771, -0.3602]], requires_grad=True)
tensor(10.2915, grad_fn=<MeanBackward0>)
tensor([[3.9141, 2.8859],
        [1.0844, 2.4597]])


In [ ]:
#停止梯度计算
#如果你不希望某些张量的梯度被计算（例如，当你不需要反向传播时），可以使用 torch.no_grad() 或设置 requires_grad=False。
# 使用 torch.no_grad() 禁用梯度计算
with torch.no_grad():
    y = x * 2

In [11]:
#神经网络通过调整神经元之间的连接权重来优化预测结果，这一过程涉及前向传播、损失计算、反向传播和参数更新。
# PyTorch 提供了 nn 模块，可以方便地构建神经网络。
import torch.nn as nn
import torch.optim as optim

# 定义一个简单的全连接神经网络
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # 输入层到隐藏层
        self.fc2 = nn.Linear(2, 1)  # 隐藏层到输出层
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))  # ReLU 激活函数
        x = self.fc2(x)
        return x

# 创建网络实例
model = SimpleNN()

# 打印模型结构
print(model)

# 随机输入
x = torch.randn(1, 2)

# 前向传播
output = model(x)
print(output)

# 定义损失函数（例如均方误差 MSE）
criterion = nn.MSELoss()

# 假设目标值为 1
target = torch.randn(1, 1)

# 计算损失
loss = criterion(output, target)
print(loss)

'''
优化器在训练过程中更新神经网络的参数，以减少损失函数的值。

PyTorch 提供了多种优化器，例如 SGD、Adam 等。

使用优化器进行参数更新：
'''
# 定义优化器（使用 Adam 优化器）
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 训练步骤
optimizer.zero_grad()  # 清空梯度
loss.backward()  # 反向传播
optimizer.step()  # 更新参数

SimpleNN(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)
tensor([[0.6293]], grad_fn=<AddmmBackward0>)
tensor(6.1912, grad_fn=<MseLossBackward0>)


NameError: name 'model' is not defined